version: '3'

services:
  php:
    build: ./backend/php
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html

  nginx:
    build: ./backend/nginx
    ports:
      - 80:80
    volumes:
      - ./app/public:/var/www/html/public
    depends_on:
      - php
